// Generated by fixtures/generate.ts from models.dev. Do not edit by hand.
//
// Rates are Ticks per million tokens: integers of 1e-10 USD, so nothing here
// is a float and nothing rounds twice. A rate is what a vendor publishes and
// never what a Run was billed.
import type { ModelPrice } from "@missingstudio/eva-schema"

export interface PriceSeed extends ModelPrice {
  readonly provider: string
  readonly model: string
}

// The date this snapshot was taken. A fact about a moving thing carries the
// day it was checked, the way the protocol pin carries its release.
export const CHECKED_AT = "2026-08-15"
export const SOURCE = "https://models.dev"

export const PRICES: readonly PriceSeed[] = [
  {
    provider: "anthropic",
    model: "claude-fable-5",
    inputTicks: 100000000000,
    outputTicks: 500000000000,
    cacheReadTicks: 10000000000,
    cacheWriteTicks: 125000000000,
  },
  {
    provider: "anthropic",
    model: "claude-haiku-4-5",
    inputTicks: 10000000000,
    outputTicks: 50000000000,
    cacheReadTicks: 1000000000,
    cacheWriteTicks: 12500000000,
  },
  {
    provider: "anthropic",
    model: "claude-haiku-4-5-20251001",
    inputTicks: 10000000000,
    outputTicks: 50000000000,
    cacheReadTicks: 1000000000,
    cacheWriteTicks: 12500000000,
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-5",
    inputTicks: 50000000000,
    outputTicks: 250000000000,
    cacheReadTicks: 5000000000,
    cacheWriteTicks: 62500000000,
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-5-20251101",
    inputTicks: 50000000000,
    outputTicks: 250000000000,
    cacheReadTicks: 5000000000,
    cacheWriteTicks: 62500000000,
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-6",
    inputTicks: 50000000000,
    outputTicks: 250000000000,
    cacheReadTicks: 5000000000,
    cacheWriteTicks: 62500000000,
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-7",
    inputTicks: 50000000000,
    outputTicks: 250000000000,
    cacheReadTicks: 5000000000,
    cacheWriteTicks: 62500000000,
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-8",
    inputTicks: 50000000000,
    outputTicks: 250000000000,
    cacheReadTicks: 5000000000,
    cacheWriteTicks: 62500000000,
  },
  {
    provider: "anthropic",
    model: "claude-opus-5",
    inputTicks: 50000000000,
    outputTicks: 250000000000,
    cacheReadTicks: 5000000000,
    cacheWriteTicks: 62500000000,
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-5",
    inputTicks: 30000000000,
    outputTicks: 150000000000,
    cacheReadTicks: 3000000000,
    cacheWriteTicks: 37500000000,
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-5-20250929",
    inputTicks: 30000000000,
    outputTicks: 150000000000,
    cacheReadTicks: 3000000000,
    cacheWriteTicks: 37500000000,
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-6",
    inputTicks: 30000000000,
    outputTicks: 150000000000,
    cacheReadTicks: 3000000000,
    cacheWriteTicks: 37500000000,
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-5",
    inputTicks: 20000000000,
    outputTicks: 100000000000,
    cacheReadTicks: 2000000000,
    cacheWriteTicks: 25000000000,
  },
]
