// Regenerates the price snapshot from models.dev. Run deliberately, review
// the diff, and commit: `bun plugins/catalog-prices/fixtures/generate.ts`
//
// The snapshot is vendored rather than fetched, because boot does no network
// and a rate Eva shows should be the one a reader can see in the diff. The
// suite fails when a model the catalog seeds has no price here, so a stale
// snapshot is loud rather than silent.
import { writeFileSync } from "node:fs"
import { fetchModels } from "tokenlens"

const PROVIDERS = ["anthropic", "openai"] as const

const providers = await fetchModels()

const ticks = (usd: number | null | undefined): number | undefined =>
  usd == null ? undefined : Math.round(usd * 1e10)

const rows: string[] = []
for (const provider of PROVIDERS) {
  const models = providers[provider]?.models ?? {}
  for (const [id, model] of Object.entries(models).sort(([a], [b]) => (a < b ? -1 : 1))) {
    // models.dev names its rates in USD per million tokens.
    const cost = (model as { cost?: Partial<Record<string, number>> }).cost ?? {}
    const input = ticks(cost["input"])
    const output = ticks(cost["output"])
    if (input === undefined || output === undefined) continue
    // A zero rate names an embedding or image model, not a completion. The
    // catalog offers none of them, and the snapshot's own invariants hold
    // every rate above zero.
    if (input <= 0 || output <= 0) continue
    // A zero cache rate means the vendor offers no caching there, so the
    // field stays absent rather than naming a free rate.
    const cacheRead = ticks(cost["cache_read"])
    const cacheWrite = ticks(cost["cache_write"])
    const fields = [
      `inputTicks: ${input}`,
      `outputTicks: ${output}`,
      ...(cacheRead === undefined || cacheRead <= 0 ? [] : [`cacheReadTicks: ${cacheRead}`]),
      ...(cacheWrite === undefined || cacheWrite <= 0 ? [] : [`cacheWriteTicks: ${cacheWrite}`]),
    ]
    rows.push(`  { provider: "${provider}", model: "${id}", ${fields.join(", ")} },`)
  }
}

const checked = new Date().toISOString().slice(0, 10)

const source = `// Generated by fixtures/generate.ts from models.dev. Do not edit by hand.
//
// Rates are Ticks per million tokens: integers of 1e-10 USD, so nothing here
// is a float and nothing rounds twice. A rate is what a vendor publishes and
// never what a Run was billed.
import type { ModelPrice } from "@missingstudio/eva-schema"

export interface PriceSeed extends ModelPrice {
  readonly provider: string
  readonly model: string
}

// The date this snapshot was taken. A fact about a moving thing carries the
// day it was checked, the way the protocol pin carries its release.
export const CHECKED_AT = "${checked}"
export const SOURCE = "https://models.dev"

export const PRICES: readonly PriceSeed[] = [
${rows.join("\n")}
]
`

writeFileSync(new URL("../src/prices.ts", import.meta.url), source)
console.log(`wrote ${rows.length} prices, checked ${checked}`)
